= Folder structure

Here are the top level directories you give the most amount of attention:

== `notes/`
Where the notes is stored, obviously. Inside of this directory are subdirectories of 
subjects in https://en.wikipedia.org/wiki/Letter_case#Special_case_styles[kebab case]
and a https://www.sqlite.org/[SQLite] database named `notes.db` where it contains
the data for the subjects and notes that are formally added into the binder.

Within those subdirectories are where the LaTeX notes are stored. In any case, 
think of the `notes/` directory as a 
http://theoldenchapters.com/organized-college-binder/[college binder notebook]. In fact, 
any subsequent reference to this directory shall be referred to as the *binder*.

Each subdirectory should have also have the following:

- A directory named `graphics/` where all of the images to be used 
within the files are stored. 
- A symbolic link from `stylesheets/` folder.

You can compile the subject notes individually (provided that your LaTeX files are
configured correctly).

== `stylesheets/`
Where my custom LaTeX style (`.sty`) and class (`.cls`) are stored. It got its name 
since I'm primarily familiar with web dev't and it just makes sense (at least for me).
Also, it may be referred to as the *stylesheets directory*.

Take note that the LaTeX files from the `notes/` directory does use packages from here 
but without referring to the relative or absolute directory since every individual
subjects in the binder has a https://kb.iu.edu/d/abbe[symbolic link] to this folder.
Hence, every package in here has to be prepended with `stylesheets/` when being
referred.

You can take a look at some of my LaTeX style files to see a template/pattern in case
you want to add your own. Unfortunately, if you have added some of your own and intended to
include in every document, don't forget to manually add in the newly package to the
